### ISSUE TITLE
issues after data updates

### ISSUE THREAD

**Issue by jspeis** [DataUSA/datausa-tracker#278]
just going to jot some quick notes on things that appear broken on the site after updating PUMS/IPEDS etc will just want to confirm where the errors are happening (if issue with data or something that needs to be updated in site).

### Dimension Updates
 - [x] new place of births in topojson (#276)
 - [x] re-run Occupation search table (#276)
 - [x] re-run Industry search table (#276)
 - [x] re-run CIP search table
 - [x] re-run University search table

### Crosswalk Related
- [x] new similar universities (#274)
- [x] PUMS to BLS industries
- [x] PUMS to BLS occupations

### Sitewide
* [x] Suffolk county MA never loads https://iron.datausa.io/profile/geo/suffolk-county-ma (looks like there's an error in pm2 logs)
* [x] [computer science](https://iron.datausa.io/profile/cip/computer-science-6) tuition data reads as N/A but [looks like data is in the cube?](https://iron-api.datausa.io/ui/#eyJkcmlsbERvd25zIjpbWyJZZWFyIiwiWWVhciIsIlllYXIiXV0sImN1dHMiOltbWzIwMTddLFsiWWVhciIsIlllYXIiLCJZZWFyIl1dLFtbIjExMDcwMSJdLFsiQ0lQIiwiQ0lQIiwiQ0lQNiJdXV0sImN1YmUiOiJpcGVkc190dWl0aW9uX2J5X2NpcCIsIm1lYXN1cmVzIjpbIkRpc3RyaWN0IFR1aXRpb24iLCJPdXQgT2YgU3RhdGUgVHVpdGlvbiIsIlN0YXRlIFR1aXRpb24iXX0=)
* [x] [construction group](https://iron.datausa.io/profile/naics/construction-group) first two sections vizs show no data
* [x] hospitals profile shown on homepage (redirect?)

**Comment by davelandry** [comment]
Search dimension update results:
 - PUMS Industry - 18 new
 - PUMS Occupation - 139 new
 - CIP - no change
 - University - 128 new

**Comment by davelandry** [comment]
Confirmed birthplace map is showing the new birthplaces, as well as fixed all other bugs! (thanks @jspeis)

I'm deploying on the server now for further testing.
