### ISSUE TITLE
acs etl 1.0

### ISSUE THREAD

**Issue by hwchen** [DataUSA/datausa-tracker#74]
Work needed to run the etl for 1.0 run:

- [x] non-agg tables work. See #73 . This is most important, because we need to make sure to get all the vars in the fetch, otherise I'll have to go through to check which are available, or redo entire fetch (20hrs plus).
  - [x] gini
  - [x] median tables simple
  - [x] median tables complex (occupation/industry) B24032, etc.
- [x] calculate mean travel time. See #72 
- [x] reshape race and ethnicity tables. See #73 for more description. But basically concat all race/ethnicity/total tables together into one big table.
- [x] remove ethnicity hispanic/nonhispanic calculation.
- [x] finish ingest portion of etl
- [x] limit ingest to 2013 in configs
- [x] `acs_ygh_health_care_coverage_overall` etl and reintroduce schema
- [x] tag aggregation type in config for schema (note non-agg tables in below comment)
